# Generated by Django 3.2.6 on 2021-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
