# Generated by Django 3.2.1 on 2021-08-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_answer_question_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_word',
            new_name='word',
        ),
    ]
