# Generated by Django 3.2.6 on 2021-08-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
